# Generated by Django 3.0.6 on 2020-09-10 16:37

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200910_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='post_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 10, 16, 37, 13, 10595, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
